
#==============================================================================
# START!!! 921_predict_0218-1.py    PID: 2500    time: 2019-02-18 04:20:50.431368
#==============================================================================

instance-1  START 921_predict_0218-1.py  time: 0.00min
SEED: 8369
0 ../data/train_f002.f
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:08<00:00,  8.22s/it]
no dup :) 
X_train.shape (8921483, 287)
CAT: ['f002_Census_OSBranch', 'f002_Census_FlightRing', 'f002_Census_ProcessorManufacturerIdentifier', 'f002_Census_ProcessorModelIdentifier', 'f002_Processor', 'f002_CityIdentifier', 'f002_Census_ProcessorClass', 'f002_GeoNameIdentifier', 'f002_Census_OSSkuName', 'f002_Census_ActivationChannel', 'f002_OsBuildLab', 'f002_Census_OEMModelIdentifier', 'f002_Census_InternalBatteryType', 'f002_OsSuite', 'f002_Census_PowerPlatformRoleName', 'f002_AVProductStatesIdentifier', 'f002_Census_OSWUAutoUpdateOptionsName', 'f002_Platform', 'f002_Census_FirmwareManufacturerIdentifier', 'f002_OsBuildLab_minor', 'f002_Census_MDC2FormFactor', 'f002_OrganizationIdentifier', 'f002_OsPlatformSubRelease', 'f002_DefaultBrowsersIdentifier', 'f002_Census_OSInstallLanguageIdentifier', 'f002_Census_OEMNameIdentifier', 'f002_Census_DeviceFamily', 'f002_Census_FirmwareVersionIdentifier', 'f002_LocaleEnglishNameIdentifier', 'f002_IeVerIdentifier', 'f002_OsBuildLab_architecture', 'f002_SkuEdition', 'f002_SmartScreen', 'f002_Census_PrimaryDiskTypeName', 'f002_Census_ChassisTypeName', 'f002_Census_OSEdition', 'f002_Census_GenuineStateName', 'f002_Census_OSInstallTypeName', 'f002_Census_OSUILocaleIdentifier', 'f002_CountryIdentifier', 'f002_ProductName', 'f002_OsBuild', 'f002_OsVer', 'f002_OsBuildLab_build', 'f002_Census_OSArchitecture', 'f002_Wdft_RegionIdentifier', 'f002_OsBuildLab_major']
[LightGBM] [Warning] num_threads is set with nthread=-1, will be overridden by n_jobs=-1. Current value: num_threads=-1
[LightGBM] [Warning] Unknown parameter: silent
[LightGBM] [Warning] Unknown parameter: importance_type
[LightGBM] [Warning] num_threads is set with nthread=-1, will be overridden by n_jobs=-1. Current value: num_threads=-1
[LightGBM] [Warning] Unknown parameter: silent
[LightGBM] [Warning] Unknown parameter: importance_type
[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] Number of positive: 4458892, number of negative: 4462591
[LightGBM] [Info] Total Bins 23379
[LightGBM] [Info] Number of data: 8921483, number of used features: 287
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499793 -> initscore=-0.000829
[LightGBM] [Info] Start training from score -0.000829
0 ../data/test_f002.f
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:05<00:00,  5.31s/it]
no dup :) 
X_test.shape (7853253, 287)
corr with best
with mybest: 0.7313100291263579
with nejumi: 0.8181902555261147

# =============================================================================
# write down these info to benchmark.xlsx
# =============================================================================

file                     : ../output/0218-1.pkl
feature size             : 287
category feature size    : 47
nfold                    : -
seed                     : 8369
eta                      : 0.05
NROUND                   : 17329

# =============================================================================

rm: cannot remove '../output/0218-1_8369.pkl.gz': No such file or directory
submit
Traceback (most recent call last):
  File "/home/Kazuki/anaconda3/bin/kaggle", line 10, in <module>
    sys.exit(main())
  File "/home/Kazuki/anaconda3/lib/python3.6/site-packages/kaggle/cli.py", line 51, in main
    out = args.func(**command_args)
  File "/home/Kazuki/anaconda3/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 524, in competition_submit_cli
    competition, quiet)
  File "/home/Kazuki/anaconda3/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 475, in competition_submit
    content_length=os.path.getsize(file_name),
  File "/home/Kazuki/anaconda3/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '../output/0218-1.pkl'
SCORE!!!
fileName: 0216-1.csv.gz
date: 2019-02-16 07:06:43
description: nejumi + f007
status: complete
publicScore: 0.692
privateScore: None

#==============================================================================
# SUCCESS !!! 921_predict_0218-1.py
#==============================================================================

time: 355.46min
instance-1  FINISH 921_predict_0218-1.py  time: 355.46min
